### ISSUE TITLE
meta-issue: improvements to pytorch backend

### ISSUE THREAD

**Issue by jpata** [jpata/particleflow#203]
- [x] use tfds dataset for pytorch: #201
  - [x] use Ray for distributing, monitoring and resuming training
  - [ ] allow long-running trainings to be resumed in the middle of the epoch
  - [x] implement GNN LSH model in pytorch
  - [x] support fp16 and bf16 mixed-precision training

**Comment by jpata** [comment]
tfds for pytorch was implemented in #228.

**Comment by jpata** [comment]
Generally speaking this is done, pytorch is now the main training backend.
